2025-08-29 Regressions Fixes (#1774)
* [Hotfix] Don't fail to enumerate file trees with broken symlink.

Resolves the 'fastdds' failures observed in https://github.com/microsoft/vcpkg/pull/47130

Note that the POSIX version of these functions already filter for ENOENT and ENOTDIR:

                                    if (::stat(full.c_str(), &s) != 0)
                                    {
                                        if (errno == ENOENT || errno == ENOTDIR)
                                        {
                                            ec.clear();
                                        }

* Add a Linux cmake preset that does not require node.js to be installed.

* [Hotfix] Don't fail to enumerate file trees with recursive symlinks

Fixes the wcslib:x64-android failures.

* [Hotfix] Harden filesystem ops in write_sbom.

Hopefully fixes:

error: open_for_read("/mnt/vcpkg-ci/p/salome-configuration_x64-linux/share/salome-configuration/copyright/modules.info"): Permission denied