Add CMAKE_DL_LIBS for dlopen/dlsym.
Hopefully resolves build failures like: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=12288570

```console
: && /usr/bin/g++ --sysroot=/crossrootfs/arm64 -isystem /crossrootfs/arm64/usr/include/aarch64-linux-gnu/c++/9 -isystem /crossrootfs/arm64/usr/include/c++/9 -B/crossrootfs/arm64/usr/lib/aarch64-linux-gnu/ -isystem /crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/include-fixed -isystem /crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/include -isystem /crossrootfs/arm64/usr/include/aarch64-linux-gnu -isystem /crossrootfs/arm64/usr/include -static-libgcc -nostdinc -static-libstdc++ -L/crossrootfs/arm64/usr/lib/gcc/aarch64-linux-gnu/9/ -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-declarations -Wno-dangling-reference -Werror -O3 -DNDEBUG -Wl,--rpath-link=/crossrootfs/arm64/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/arm64/usr/lib/aarch64-linux-gnu -L/crossrootfs/arm64/usr/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/arm64/lib/aarch64-linux-gnu -Wl,--rpath-link=/crossrootfs/arm64/usr/lib/aarch64-linux-gnu -L/crossrootfs/arm64/usr/lib/aarch64-linux-gnu CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/cmd-parser.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/diagnostics.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/git.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/message_sinks.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/parse.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/strings.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/stringview.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/system.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/system.deviceid.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/system.mac.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/system.process.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/system.proxy.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/uint128.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/unicode.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/uuid.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/base/xmlserializer.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/binaryparagraph.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/buildenvironment.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/bundlesettings.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/cgroup-parser.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/ci-baseline.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/ci-feature-baseline.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/cmakevars.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.acquire-project.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.acquire.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.activate.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.add-version.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.add.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.autocomplete.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.bootstrap-standalone.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.build-external.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.build.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.check-support.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci-clean.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci-verify-versions.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.contact.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.create.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.deactivate.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.depend-info.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.download.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.edit.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.env.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.export.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.fetch.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.find.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.format-feature-baseline.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.format-manifest.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.generate-msbuild-props.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.hash.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.help.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.init-registry.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.install.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.integrate.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.license-report.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.list.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.new.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.owns.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.package-info.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.portsdiff.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.regenerate.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.remove.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.search.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.set-installed.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.test-features.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.update-baseline.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.update-registry.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.update.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.upgrade.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.use.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.version.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.vsinstances.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-applocal.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-ce.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-changelog.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-check-tools-sha.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-extract.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-generate-message-map.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-preregister-telemetry.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-print-config.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.z-upload-metrics.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/configuration.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/configure-environment.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/input.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/metrics.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/packagespec.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/paragraphs.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/platform-expression.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/postbuildlint.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/spdx.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/statusparagraph.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/statusparagraphs.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/tools.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/triplet.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkgcmdarguments.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkglib.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkgpaths.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/versions.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/visualstudio.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/xunitwriter.cpp.o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -o vcpkg  _deps/fmt-build/libfmt.a  liblocale-resources.a  -pthread && :
/usr/bin/ld: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o: in function `(anonymous namespace)::inner(vcpkg::Filesystem const&, vcpkg::VcpkgCmdArguments const&, vcpkg::BundleSettings const&)':
vcpkg.cpp:(.text+0x47c): undefined reference to `dlopen'
/usr/bin/ld: vcpkg.cpp:(.text+0x48c): undefined reference to `dlsym'
/usr/bin/ld: vcpkg.cpp:(.text+0x494): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
mv: cannot stat '/mnt/vss/_work/_temp/build/vcpkg': No such file or directory
```