Add manifests. (#571)
This enables vcpkg to be longPathAware, opts in to current Windows behavior, and the current heap implementation.

Drive by fix for:

```
FAILED: CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o
/usr/bin/c++  -DFMT_LOCALE -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -I../include -I_deps/fmt-src/include -O3 -DNDEBUG   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-declarations -Werror -std=c++17 -MD -MT CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o -MF CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o.d -o CMakeFiles/vcpkg-fuzz.dir/src/vcpkg-fuzz/main.cpp.o -c ../src/vcpkg-fuzz/main.cpp
../src/vcpkg-fuzz/main.cpp: In function ‘int main(int, char**)’:
../src/vcpkg-fuzz/main.cpp:214:5: error: ‘args’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  214 |     switch (args.kind)
      |     ^~~~~~
cc1plus: all warnings being treated as errors
```