[x-update-baseline] Initial implementation (#341)
* start working

* update vcpkgpaths to better support what I want

* optional: make certain `get()` is only called when
  it won't result in a dangling pointer
* vcpkgpaths: remove JsonStyle support as it isn't used
* vcpkgpaths: switch from two functions returning
  Optional<Manifest> + Optional<Path>,
  to one function returning Optional<ManifestAndLocation>
* vcpkgpaths: add `get_configuration_and_location`

* rename get_*_and_location -> get_*

* lots of CRs

* get_latest_baseline -> configuration.cpp
* format
* optional - add see-through operator==
* add `--add-initial-baseline` option
* more correct if-elses

* add messages!

```
PS /../nimazzuc/projects/testproj> ../vcpkg-tool/build/vcpkg x-update-baseline --dry-run
registry 'https://github.com/microsoft/vcpkg' already up to date: 89295c9fe22e97ca9e380a6c771ccf2ff09dca95
registry '/a/b' not updated: default
registry 'https://foobar' not updated: default
warning: git failed to fetch remote repository https://foobar
Error: Failed to fetch ref HEAD from repository https://foobar.
fatal: unable to access 'https://foobar/': Could not resolve host: foobar
```

* update - hopefully fix Billy's CRs

* fix formatting

* (optional::operator==) add tests, add opt<T> == opt<U>

* rename things

* registry_location -> pretty_location
* ManifestAndLocation -> ManifestAndPath
* ConfigurationAndLocation -> ConfigurationAndSource

* minor other CRs

* forgot to to_string

* format

* I think this is what robert wants?

* format