Fix build breaks discovered on Node 18.x (#818)
* Remove calls to tests that are not present in our tar-stream fork.

* I'm not sure about the exact cause of this failure but I suspect it's a change from node version since that's the only thing we've changed:

```
  1) TarBzUnpacker
       UnpacksLegitimateSmallTarBz:
     Error: Premature close
      at new NodeError (node:internal/errors:393:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.stream.destroy (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:84:12)
      at _end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:67:14)
      at Stream.stream.end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:74:5)
      at ProgressTrackingStream.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at ProgressTrackingStream.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

  2) TarBzUnpacker
       ImplementsUnpackOptions:
     Error: Premature close
      at new NodeError (node:internal/errors:393:5)
      at Stream.<anonymous> (node:internal/streams/pipeline:352:14)
      at Stream.emit (node:events:525:35)
      at Stream.stream.destroy (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:84:12)
      at _end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:67:14)
      at Stream.stream.end (C:\Dev\vcpkg-tool\ce\common\temp\node_modules\.pnpm\through@2.3.8\node_modules\through\index.js:74:5)
      at ProgressTrackingStream.onend (node:internal/streams/readable:705:10)
      at Object.onceWrapper (node:events:627:28)
      at ProgressTrackingStream.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I'm pretty sure almost all of this compression code is filthy with how fds are treated; running the tests still gives:

```
(node:26580) Warning: Closing file descriptor 3 on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26580) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
```

In the medium term we will throw all of this out and feed it all to libarchive (either through linking vcpkg to libarchive ourselves or feeding it to `cmake -E tar`) but this targeted workaround gets my development working again.