Fix handling of z- switches.
This was discovered in smoke testing of the artifacts feature. Artifacts was unable to download anything because it passes `--z-machine-readable-progress` which failed with:

```
PS C:\Dev\vcpkg-tool> C:\Users\bion\.vcpkg\vcpkg.exe x-download c:\Users\bion\.vcpkg\downloads\vcpkg.ce.default-registry.zip --z-machine-readable-progress --skip-sha512 --url=https://aka.ms/vcpkg-ce-default
error: unexpected switch: --z-machine-readable-progress
example:
    vcpkg x-download <filepath> [--sha512=]<sha512> [--url=https://...]...
example:
    vcpkg x-download <filepath> --skip-sha512 [--url=https://...]...Options:
  --x-asset-sources=...           Add sources for asset caching. See 'vcpkg help assetcaching'.
  --binarysource=...              Add sources for binary caching. See 'vcpkg help binarycaching'.
  --x-buildtrees-root=...         (Experimental) Specify the buildtrees root directory.
  --downloads-root=...            Specify the downloads root directory.
                                  (default: VCPKG_DOWNLOADS)
  --header=...                    Additional header to use when fetching from URLs
  --host-triplet=...              Specify the host architecture triplet. See 'vcpkg help triplet'.
                                  (default: 'VCPKG_DEFAULT_HOST_TRIPLET')
  --x-install-root=...            (Experimental) Specify the install root directory.
  --overlay-ports=...             Specify directories to be used when searching for ports.
                                  (also: 'VCPKG_OVERLAY_PORTS')
  --overlay-triplets=...          Specifiy directories containing triplets files.
                                  (also: 'VCPKG_OVERLAY_TRIPLETS')
  --x-packages-root=...           (Experimental) Specify the packages root directory.
  --sha512=...                    The hash of the file to be downloaded
  --skip-sha512                   Do not check the SHA512 of the downloaded file
  --store                         Indicates the file should be stored instead of fetched
  --triplet=...                   Specify the target architecture triplet. See 'vcpkg help triplet'.
                                  (default: 'VCPKG_DEFAULT_TRIPLET')
  --url=...                       URL to download and store if missing from cache
  --vcpkg-root=...                Specify the vcpkg root directory.
                                  (default: 'VCPKG_ROOT')

PS C:\Dev\vcpkg-tool>
```